-
  name: 'General Actions'
  uriPattern:    '({@action})'
  defaults:
    '@package':    'BusyNoggin.Todos'
    '@controller': 'Todo'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true